### ISSUE TITLE
An idiot using windows

### ISSUE THREAD

**Issue by hestryin** [krmax44/Playify-Transfer#1]
Hi. I'm not a coder and I'm on Windows 10. I tried using the "pre-built"/standalone zip version of this. I set the password and ran playify-transfer.exe and then opened a spotify playlist. When I hit "export," playify-transfer.exe displayed the message below. As a non-programmer, I can at least see that the directories below are clearly the paths from your computer. Do I need to have python installed (and understand how to use it) in order to get the directories switched over to ones that work for my PC? Did I skip a step without realizing it? 

I realize this is probably the least intelligent "issue" that has been submitted on github ever, but I'm really hoping to get this to work!

Thanks,
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 62714)
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\socketserver.py", line 639, in process_request_thread
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\socketserver.py", line 361, in finish_request
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_server\websocket_server.py", line 167, in __init__
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\socketserver.py", line 696, in __init__
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_server\websocket_server.py", line 180, in handle
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_server\websocket_server.py", line 240, in read_next_message
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_server\websocket_server.py", line 126, in _message_received_
  File "playify-transfer.py", line 66, in receiveWS
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\gmusicapi\clients\mobileclient.py", line 130, in login
OSError: a valid MAC could not be determined. Provide an android_id (and be sure to provide the same one on future runs).
----------------------------------------

## System Information

 - Python version: 
 - OS: 
 - Transfer version:

**Comment by krmax44** [comment]
Looks like an error with the gmusicapi package. I'll have a look at the prebuilt version later, in the meantime you could try to install Python and follow the manual installation.

**Comment by hestryin** [comment]
As suggested, I did install Python and ran a manual installation. While the directories, etc. now correctly reflect the directories on my computer, I'm still getting the same OSError related to providing an "android_id." Is this the gmusicapi package error you mentioned?
