### ISSUE TITLE
Error processing requests, references invalid paths (C:\Users\Max\...)

### ISSUE THREAD

**Issue by Gnarfoz** [krmax44/Playify-Transfer#2]
## System Information
 - Python version: N/A
 - OS: Microsoft Windows [Version 10.0.16299.309]
 - Transfer version: 6f4fcf4a585726bcc581368afc568e1cba7abaf7 (standalone-v1.0)

Hi,
I downloaded the standalone version, set the password, and clicked on the transfer button in Chrome.

This results in the following output from playify-transfer.exe:
```
C:\Users\gnarf\Desktop\Playify-Transfer>playify-transfer.exe
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51570)
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\socketserver.py", line 639, in process_request_thread
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\socketserver.py", line 361, in finish_request
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_server\websocket_server.py", line 167, in __init__
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\socketserver.py", line 696, in __init__
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_server\websocket_server.py", line 178, in handle
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_server\websocket_server.py", line 294, in handshake
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 4: invalid start byte
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51584)
Traceback (most recent call last):
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\socketserver.py", line 639, in process_request_thread
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\socketserver.py", line 361, in finish_request
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_server\websocket_server.py", line 167, in __init__
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\socketserver.py", line 696, in __init__
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_server\websocket_server.py", line 178, in handle
  File "C:\Users\Max\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_server\websocket_server.py", line 294, in handshake
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x97 in position 15: invalid start byte
----------------------------------------
```

Not quite sure what to do about that, apart from trying to go the "install Python" route.

**Comment by Gnarfoz** [comment]
Actually, getting the same thing when going the manual route (albeit under WSL):

## System Information
 - Python version: Python 3.5.2
 - OS: Ubuntu 16.04.4 LTS
 - Transfer version: 8dbb298029075fb93837f71b356b08a02f9fd58e

```
gnarfoz@Alpha:~/code/Playify-Transfer$ python3 playify-transfer.py
Listening on port 5673 for clients..
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51210)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/gnarfoz/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 136, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/gnarfoz/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 147, in handle
    self.handshake()
  File "/home/gnarfoz/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 243, in handshake
    message = self.request.recv(1024).decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 4: invalid start byte
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 51221)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/gnarfoz/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 136, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/gnarfoz/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 147, in handle
    self.handshake()
  File "/home/gnarfoz/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 243, in handshake
    message = self.request.recv(1024).decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 11: invalid start byte
----------------------------------------
```

Is my browser speaking something it doesn't understand?

**Comment by Gnarfoz** [comment]
Just noticed that in both cases, 1 request results in two exception messages. Updated both posts.

**Comment by krmax44** [comment]
Maybe one of your songs or artist has a very special character in their name, or there is just a general issue with the Websocket server library. Could you send me the link of your playlist please, so I can try to reproduce the issue?

**Comment by Gnarfoz** [comment]
Sure, this is the playlist: https://open.spotify.com/user/21a7x2jo6avw7bxvyqhfjpndy/playlist/7a3XA3YED6WcIvLuzwW83x?si=ZVN6_nBRSQm219LgkblprQ

Looks like the most _exotic_ character is a boring old "é".

**Comment by krmax44** [comment]
Very weird, the conversion works without a problem for me...

**Comment by Gnarfoz** [comment]
At work, using the standalone 1.0 version, on Windows 1607, I don't get these errors, because it doesn't work for a different reason:
It is not proxy aware at all and tries to open a direct connection to Google. 😢

The assumption here is "no data = no error", though.
No idea if it would work with direct internet access.

I can't install the current master version for comparison, since on this older Windows/WSL/Ubuntu 14.04/Python 3.4, the dependencies fail to install (pip errors trying to install gmusicapi -> MechanicalSoup -> pytest-runner.
