### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 230: invalid continuation byte

### ISSUE THREAD

**Issue by haboutnnah** [krmax44/Playify-Transfer#9]
```Exception happened during processing of request from ('127.0.0.1', 60260)
Traceback (most recent call last):
  File "C:\Python37\Lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python37\Lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Hannah\git\Playify-Transfer\VirtualEnv\lib\site-packages\websocket_server\websocket_server.py", line 168, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "C:\Python37\Lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\Hannah\git\Playify-Transfer\VirtualEnv\lib\site-packages\websocket_server\websocket_server.py", line 181, in handle
    self.read_next_message()
  File "C:\Users\Hannah\git\Playify-Transfer\VirtualEnv\lib\site-packages\websocket_server\websocket_server.py", line 243, in read_next_message
    opcode_handler(self, message_bytes.decode('utf8'))
  File "C:\Users\Hannah\git\Playify-Transfer\VirtualEnv\lib\site-packages\websocket_server\websocket_server.py", line 127, in _message_received_
    self.message_received(self.handler_to_client(handler), self, msg)
  File ".\playify-transfer.py", line 12, in receiveWS
    data = json.loads(msg.encode("latin-1"))
  File "C:\Python37\Lib\json\__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 230: invalid continuation byte```
## System Information

 - Python version: Python 3.7.3
 - OS: Windows 10
 - Transfer version: Hasn't changed for two years
- I installed websocket server using git because the default version was out of date.

**Comment by haboutnnah** [comment]
It was fixed -- at line 244 of websocket_server.py (Library code), you need to c hange utf-8 to latin-1
